[build]
  command = ""
  publish = "website"

[[redirects]]
  from = "/lead-magnets/*"
  to = "/lead-magnets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
