"""
Administrative Assistant Agent for Ironhorse Collective, LLC
Handles email monitoring, meeting summaries, and daily task reporting.
"""

from datetime import datetime
from typing import Optional


class AdministrativeAssistant:
    """
    Executive support agent responsible for:
    - Email triage and daily digest
    - Meeting summary generation
    - Daily task summary reports
    - Calendar management
    - Coffee brewing (virtually, of course)
    """

    def __init__(self, name: str = "Alex Morgan"):
        self.name = name
        self.title = "Administrative Assistant"
        self.department = "Executive Support"
        self.email_inbox = []
        self.meetings = []
        self.daily_reports = []
        self.coffee_count = 0

    def triage_emails(self, emails: list) -> dict:
        """Sort incoming emails by priority and category."""
        categories = {"urgent": [], "client_inquiry": [], "internal": [], "newsletter": [], "spam": []}
        for email in emails:
            subject = email.get("subject", "").lower()
            sender = email.get("from", "").lower()
            if any(w in subject for w in ["urgent", "asap", "critical"]):
                categories["urgent"].append(email)
            elif "newsletter" in subject or "digest" in subject:
                categories["newsletter"].append(email)
            elif any(w in subject for w in ["meeting", "standup", "sync"]):
                categories["internal"].append(email)
            elif "@" in sender:
                categories["client_inquiry"].append(email)
            else:
                categories["spam"].append(email)
        return categories

    def generate_meeting_summary(self, meeting: dict) -> str:
        """Generate a structured summary from meeting notes."""
        title = meeting.get("title", "Untitled Meeting")
        date = meeting.get("date", datetime.now().strftime("%Y-%m-%d"))
        attendees = meeting.get("attendees", [])
        notes = meeting.get("notes", "")
        action_items = meeting.get("action_items", [])

        summary = "# Meeting Summary: " + title + "\n"
        summary += "**Date:** " + date + "\n"
        summary += "**Attendees:** " + ", ".join(attendees) if attendees else "TBD" + "\n\n"
        summary += "## Key Discussion Points\n"
        summary += notes if notes else "No notes recorded.\n\n"
        summary += "## Action Items\n"

        for i, item in enumerate(action_items, 1):
            owner = item.get("owner", "Unassigned")
            task = item.get("task", "")
            due = item.get("due_date", "TBD")
            summary += str(i) + ". **" + task + "** | Owner: " + owner + " | Due: " + due + "\n"

        summary += "\n---\n*Generated by " + self.name + ", " + self.title + "*\n"
        return summary

    def generate_daily_report(self, tasks: list, meetings: list, leads: int = 0) -> str:
        """Generate a daily summary report for the CEO."""
        today = datetime.now().strftime("%A, %B %d, %Y")
        completed = [t for t in tasks if t.get("status") == "completed"]
        in_progress = [t for t in tasks if t.get("status") == "in_progress"]
        pending = [t for t in tasks if t.get("status") == "pending"]

        report = "# Daily Report - " + today + "\n"
        report += "**Prepared by:** " + self.name + ", " + self.title + "\n\n"
        report += "## Task Summary\n"
        report += "- **Completed:** " + str(len(completed)) + "\n"
        report += "- **In Progress:** " + str(len(in_progress)) + "\n"
        report += "- **Pending:** " + str(len(pending)) + "\n"
        report += "- **Total:** " + str(len(tasks)) + "\n\n"
        report += "### Completed Today\n"
        for t in completed:
            report += "- DONE: " + t.get("title", "Unknown") + "\n"
        report += "\n### In Progress\n"
        for t in in_progress:
            report += "- ACTIVE: " + t.get("title", "Unknown") + "\n"
        report += "\n### Pending\n"
        for t in pending:
            report += "- QUEUED: " + t.get("title", "Unknown") + "\n"
        report += "\n## Meetings Today\n"
        report += "- Total: " + str(len(meetings)) + "\n"
        for m in meetings:
            report += "- " + m.get("title", "Untitled") + " (" + m.get("time", "TBD") + ")\n"
        report += "\n## Leads Generated\n- New leads today: " + str(leads) + "\n"
        report += "\n---\n*Next report: Tomorrow at 9:00 AM*\n"
        return report

    def brew_coffee(self, style: str = "espresso") -> str:
        """Virtually brew coffee for the team."""
        self.coffee_count += 1
        styles = {
            "espresso": "A rich, bold espresso. Perfect for a quick energy boost.",
            "latte": "A smooth latte with silky foam. Great for long meetings.",
            "americano": "A clean americano. No-nonsense, just like a good to-do list.",
            "cappuccino": "A frothy cappuccino. Because every report deserves a little indulgence.",
            "cold_brew": "Smooth cold brew. For those late-night deadline crunches.",
        }
        brew = styles.get(style, styles["espresso"])
        return self.name + " is brewing: " + brew + " (Coffee #" + str(self.coffee_count) + " of the day)"

    def get_status(self) -> dict:
        """Return agent status."""
        return {
            "name": self.name,
            "title": self.title,
            "department": self.department,
            "emails_processed": len(self.email_inbox),
            "meetings_summarized": len(self.meetings),
            "reports_generated": len(self.daily_reports),
            "coffee_brewed": self.coffee_count,
            "status": "active",
        }


if __name__ == "__main__":
    asst = AdministrativeAssistant()
    print("Administrative Assistant " + asst.name + " is online.")
    print(asst.brew_coffee("latte"))
    print(asst.get_status())
